Contrast:
  contrast: 0.5   # [0,1]
Sharpening:
Brightness:
   brightness: -100 #[-127, 127]
Resize:
  height: 500
  width: 500
Red:
Flip: 1 #1 - mirror, -1 upside down, 0- upside down and mirror
Rotation: 90 #angle of rotation
Rotation_library: 13 #angle of rotation
Grayscale:
Chain_processing: False #True or False
